function simulated_gene_expression = generate_simulated_curves_from_clusters(list_of_cluster_means, gene_expression_by_cluster)

  simulated_gene_expression = [];

  for cluster_index = 1:size(list_of_cluster_means,1)

    mean_of_current_cluster = list_of_cluster_means(cluster_index,:);
    
    std_of_genes_in_current_cluster = std(gene_expression_by_cluster{cluster_index},1);

    number_of_genes_in_current_cluster = size(gene_expression_by_cluster{cluster_index},1);
    
    % The simulated curves for each gene in this cluster are generated by adding noise to the mean of the cluster.
    % The noise per time point a Gaussian noise with the standard deviation (per time point) from the original cluster.
    for current_gene_index=1:number_of_genes_in_current_cluster
      
      % The following two lines are equivalent.
%        expression_of_current_simulated_gene = mean_of_current_cluster + normrnd(0, std_of_genes_in_current_cluster);
      expression_of_current_simulated_gene = normrnd(mean_of_current_cluster, std_of_genes_in_current_cluster);
      
      simulated_gene_expression = [simulated_gene_expression; expression_of_current_simulated_gene];
      
    end
  
  end

end

